import type { Metadata } from "next";
import { Nunito, Zain } from "next/font/google";
import "./globals.css";


const nunito = Nunito({
  variable: "--font-nunito",
  subsets: ["latin"],
})

const zain = Zain({
  variable: "--font-zain",
  weight: ["200","300","400","700","800","900"]
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body
        className={`${nunito.variable} ${zain.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
